### ISSUE TITLE
Написание основного окна

### ISSUE THREAD

**Issue by mr-RiP** [MaslovRG/cmddev#5]
Написание основного окна пользовательского интерфейса.

1. Основное окно
1.а. Список групп, переключается между локальным и глобальным
1.б. Таблица свойств выбранной группы
1.в. Кнопка для открытия окна настроек облака (логин/пасс/путь к рабочей папке)
1.г. Полоса состояния (внизу, показывает, что программа сейчас делает)
1.д. Панель управления
1.е. Флаг синхронизации выбранной группы

**Comment by Oreder** [comment]
Just forget the last stuff (maybe) @mr-RiP check!
